api_platform:
    title: TissupAPI
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
