services:
    php:
        image: ${PROJECT_NAME}-app-php
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
            DATABASE_URL: ${DATABASE_URL}
            ROOT_PASSWORD: ${ROOT_PASSWORD}
            DB_NAME: ${DB_NAME}
        volumes:
            - ./:/app
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - target: 80
              published: ${HTTP_PORT:-80}
              protocol: tcp
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
            - target: 443
              published: ${HTTP3_PORT:-443}
              protocol: udp
    db:
        image: mysql:8.1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"
volumes:
    caddy_data:
    caddy_config:
