services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - "./:/usr/src/app"
        restart: on-failure
        depends_on:
            - db
        networks:
            - tissup-api
    nginx:
        build: nginx:latest
        restart: on-failure
        volumes:
            - "./:/usr/src/app"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - tissup-api

    db:
        image: mysql:8.1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - tissup-api
volumes:
    db_data:

networks:
    tissup-api:
        driver: bridge
