services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php-api
        volumes:
            - "./:/usr/src/app"
        restart: on-failure
        user: 1000:1000
        ports:
            - "9000:9000"
        depends_on:
            - db
        networks:
            - tissup-api
    nginx:
        image: nginx:latest
        restart: on-failure
        volumes:
            - "./:/usr/src/app"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        networks:
            - tissup-api

    db:
        image: mysql:8.1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"
        networks:
            - tissup-api
networks:
    tissup-api:
        driver: bridge
