name: Build Image and Push Registry

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Update .env before build
        run: |
          echo "Updating .env"
          sed -i 's/^ROOT_PASSWORD=.*/ROOT_PASSWORD="'${ROOT_PASSWORD}'"/' .env
          sed -i 's/^JWT_PASSPHRASE=.*/JWT_PASSPHRASE="'${JWT_PASSPHRASE}'"/' .env
          sed -i 's/^APP_ENV=.*/APP_ENV="'prod'"/' .env

      - name: Build Docker Image PHP
        run: docker build -f docker/php/Dockerfile -t $REGISTRY_NAME/tissup-api --target prod .

      - name: Log in to Docker Registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_NAME -u $REGISTRY_USERNAME --password-stdin

      - name: Push Docker Image PHP
        run: docker push $REGISTRY_NAME/tissup-api

      - name: Build Docker Image NGINX
        run: docker build -f docker/nginx/Dockerfile -t $REGISTRY_NAME/nginx-tissup .

      - name: Push Docker Image NGINX
        run: docker push $REGISTRY_NAME/nginx-tissup
