name: Build Image and Push Registry

on:
  push:
    branches: ["feat-refresh-serverweb"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Update .env before build
        run: |
          echo "Updating .env"
          sed -i 's/^ROOT_PASSWORD=.*/ROOT_PASSWORD="'${ROOT_PASSWORD}'"/' .env
          sed -i 's/@db\//@mysqlDb\//g' .env
      - name: Build Docker Image
        run: docker build -t $REGISTRY_NAME/tissup-api .

      - name: Log in to Docker Registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_NAME -u $REGISTRY_USERNAME --password-stdin

      - name: Push Docker Image
        run: docker push $REGISTRY_NAME/tissup-api
