name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Image and Push Registry"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      SERVER_NAME: ${{ vars.SERVER_NAME }}
      TLS: ${{ vars.TLS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh $VPS_USER@$VPS_IP << EOF
          echo "--Login to registry--"
          echo $REGISTRY_PASSWORD | docker login $REGISTRY_NAME -u $REGISTRY_USERNAME --password-stdin

          echo "--Pull image--"
          docker pull $REGISTRY_NAME/tissup-api

          echo "--Stop and remove container--"
          sudo docker stop tissup-api-container || true
          sudo docker rm tissup-api-container || true

          echo "--Run new container--"
          sudo docker run -d -e SERVER_NAME=$SERVER_NAME -e TLS=$TLS -p 8001:443 -v /etc/Tissup:/app/frankenphp --name tissup-api-container $REGISTRY_NAME/tissup-api

          echo "--Add at network--"
          docker network connect tissup-api_default tissup-api-container
          EOF
