name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Image and Push Registry"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts

      - name: Deploy and Update .env
        run: |
          ssh $VPS_USER@$VPS_IP << 'EOF'
            echo "--Pull image--"
            sudo docker pull $REGISTRY_NAME/tissup-api

            echo "--Stop and remove container--"
            sudo docker stop tissup-api-container || true
            sudo docker rm tissup-api-container || true

            echo "--Run new container--"
            sudo docker run -p 8001:80 --name tissup-api-container -d $REGISTRY_NAME/tissup-api

            echo "--Copy .env out of container--"
            sudo docker cp tissup-api-container:/app/.env ~/temp.env

            echo "--Update .env variable--"
            sed -i 's/^ROOT_PASSWORD=.*/ROOT_PASSWORD="'${ROOT_PASSWORD}'"/' ~/temp.env

            echo "--Copy updated .env back to container--"
            sudo docker cp ~/temp.env tissup-api-container:/app/.env

            echo "--Dump env--"
            sudo docker exec tissup-api-container composer dump-env prod
          EOF
